# Generated by Django 3.1 on 2021-03-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('DirectoryId', models.CharField(default='', max_length=10)),
                ('qno', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=300)),
                ('option2', models.CharField(max_length=300)),
                ('option3', models.CharField(max_length=300)),
                ('option4', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Quizname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('DirectoryId', models.CharField(default='', max_length=10)),
                ('vaildfrom', models.DateField(default='2010-04-10')),
                ('vaildto', models.DateField(default='2012-06-10')),
            ],
        ),
    ]
