# Generated by Django 3.1 on 2021-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0002_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='DirectoryId',
            field=models.CharField(default='', max_length=10),
        ),
    ]
