# Generated by Django 3.1 on 2021-02-18 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('adjustment_points', models.IntegerField(default=0)),
                ('is_shadow_banned', models.BooleanField(default=False)),
                ('downvoted_answers', models.ManyToManyField(related_name='downvoted_users', to='main.Answer')),
                ('downvoted_questions', models.ManyToManyField(related_name='downvoted_users', to='main.Question')),
                ('upvoted_answers', models.ManyToManyField(related_name='upvoted_users', to='main.Answer')),
                ('upvoted_questions', models.ManyToManyField(related_name='upvoted_users', to='main.Question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
